In [1]:
import numpy as np
import pandas as pd
import sys

In [2]:
index = [('California', 2000), ('California', 2010),
         ('New York', 2000), ('New York', 2010),
         ('Texas', 2000), ('Texas', 2010)]
populations = [33871648, 37253956,
               18976457, 19378102,
               20851820, 25145561]

In [3]:
index

[('California', 2000),
 ('California', 2010),
 ('New York', 2000),
 ('New York', 2010),
 ('Texas', 2000),
 ('Texas', 2010)]

In [4]:
populations

[33871648, 37253956, 18976457, 19378102, 20851820, 25145561]

In [5]:
index

[('California', 2000),
 ('California', 2010),
 ('New York', 2000),
 ('New York', 2010),
 ('Texas', 2000),
 ('Texas', 2010)]

In [6]:
type(index)

list

In [8]:
type(index[0])

tuple

In [9]:
type(index[0][0])

str

In [10]:
type(index[0][1])

int

In [11]:
pop = pd.Series(populations,index=index)

In [12]:
pop

(California, 2000)    33871648
(California, 2010)    37253956
(New York, 2000)      18976457
(New York, 2010)      19378102
(Texas, 2000)         20851820
(Texas, 2010)         25145561
dtype: int64

In [13]:
index = pd.MultiIndex.from_tuples(index)

In [14]:
index

MultiIndex([('California', 2000),
            ('California', 2010),
            (  'New York', 2000),
            (  'New York', 2010),
            (     'Texas', 2000),
            (     'Texas', 2010)],
           )

In [15]:
index.labels

/usr/local/Cellar/ipython/7.8.0/libexec/vendor/lib/python3.7/site-packages/ipykernel_launcher.py:1: FutureWarning: .labels was deprecated in version 0.24.0. Use .codes instead.
  """Entry point for launching an IPython kernel.


FrozenList([[0, 0, 1, 1, 2, 2], [0, 1, 0, 1, 0, 1]])

In [16]:
index.codes

FrozenList([[0, 0, 1, 1, 2, 2], [0, 1, 0, 1, 0, 1]])

In [18]:
index.levels

FrozenList([['California', 'New York', 'Texas'], [2000, 2010]])

In [19]:
pop.reindex(index)

California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [20]:
pop

(California, 2000)    33871648
(California, 2010)    37253956
(New York, 2000)      18976457
(New York, 2010)      19378102
(Texas, 2000)         20851820
(Texas, 2010)         25145561
dtype: int64

In [21]:
pop = pop.reindex(index)

In [22]:
pop

California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [23]:
pop.unstack()

2000      2010
California  33871648  37253956
New York    18976457  19378102
Texas       20851820  25145561

In [24]:
pop.stack()

AttributeError: 'Series' object has no attribute 'stack'

In [25]:
pop

California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [26]:
pop[:,:]

California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [27]:
pop[:,2000]

California    33871648
New York      18976457
Texas         20851820
dtype: int64

In [28]:
pop[:,2010]

California    37253956
New York      19378102
Texas         25145561
dtype: int64

In [30]:
pop[:,'California']

KeyError: 'California'

In [31]:
pop

California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [32]:
pop['California']

2000    33871648
2010    37253956
dtype: int64

In [41]:
pop['California']

2000    33871648
2010    37253956
dtype: int64

In [42]:
type(pop['California'])

pandas.core.series.Series

In [43]:
pop['California'].loc[2000:]

2000    33871648
2010    37253956
dtype: int64

In [44]:
pop['California'].loc[2010:]

2010    37253956
dtype: int64

In [47]:
type(pop.loc[:,2000])

pandas.core.series.Series

In [49]:
pop.loc[:,2000]['New York':]

New York    18976457
Texas       20851820
dtype: int64

In [50]:
pop.loc[:,2000].iloc[:-1]

California    33871648
New York      18976457
dtype: int64

In [51]:
pop.unstack().stack()

California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [52]:
pop.unstack()

2000      2010
California  33871648  37253956
New York    18976457  19378102
Texas       20851820  25145561

In [53]:
pop

California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [54]:
pop_df = pd.DataFrame({'total': pop,
                       'under18': [9267089, 9284094,
                                   4687374, 4318033,
                                   5906301, 6879014]})
pop_df

total  under18
California 2000  33871648  9267089
           2010  37253956  9284094
New York   2000  18976457  4687374
           2010  19378102  4318033
Texas      2000  20851820  5906301
           2010  25145561  6879014

In [55]:
pop_df.unstack()

total            under18         
                2000      2010     2000     2010
California  33871648  37253956  9267089  9284094
New York    18976457  19378102  4687374  4318033
Texas       20851820  25145561  5906301  6879014

In [58]:
type(pop_df)

pandas.core.frame.DataFrame

In [59]:
type(pop_df['total'])

pandas.core.series.Series

In [60]:
type(pop_df['under18'])

pandas.core.series.Series

In [61]:
pop_df['under18']

California  2000    9267089
            2010    9284094
New York    2000    4687374
            2010    4318033
Texas       2000    5906301
            2010    6879014
Name: under18, dtype: int64

In [62]:
pop_df['under18',2000]

KeyError: ('under18', 2000)

In [64]:
pop_df['under18'][:,2000]

California    9267089
New York      4687374
Texas         5906301
Name: under18, dtype: int64

In [65]:
pop_df.iloc[0]

total      33871648
under18     9267089
Name: (California, 2000), dtype: int64

In [66]:
pop_df.iloc[1]

total      37253956
under18     9284094
Name: (California, 2010), dtype: int64

In [67]:
f_u18 = pop_df['under18']/pop_df['total']

In [68]:
type(f_u18)

pandas.core.series.Series

In [69]:
f_u18

California  2000    0.273594
            2010    0.249211
New York    2000    0.247010
            2010    0.222831
Texas       2000    0.283251
            2010    0.273568
dtype: float64

In [70]:
f_u18.index

MultiIndex([('California', 2000),
            ('California', 2010),
            (  'New York', 2000),
            (  'New York', 2010),
            (     'Texas', 2000),
            (     'Texas', 2010)],
           )

In [71]:
type(pop_df)

pandas.core.frame.DataFrame

In [72]:
df = pd.DataFrame(np.random.rand(4,2),index = [['a','a','b','b'],[1,2,1,2]])

In [73]:
df

0         1
a 1  0.072761  0.030183
  2  0.182811  0.409716
b 1  0.405248  0.821675
  2  0.006348  0.048741

In [74]:
df.columns

RangeIndex(start=0, stop=2, step=1)

In [75]:
type(df.columns)

pandas.core.indexes.range.RangeIndex

In [76]:
df.columns = pd.Index(['data1','data2'])

In [77]:
df

data1     data2
a 1  0.072761  0.030183
  2  0.182811  0.409716
b 1  0.405248  0.821675
  2  0.006348  0.048741

In [80]:
df.columns = ['data11','data12']

In [81]:
df

data11    data12
a 1  0.072761  0.030183
  2  0.182811  0.409716
b 1  0.405248  0.821675
  2  0.006348  0.048741

In [82]:
pop

California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [83]:
pop.index

MultiIndex([('California', 2000),
            ('California', 2010),
            (  'New York', 2000),
            (  'New York', 2010),
            (     'Texas', 2000),
            (     'Texas', 2010)],
           )

In [84]:
pop.index.name = ['state','year']

In [85]:
pop

California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [86]:
pop.index.names = ['state','year']

In [87]:
pop

state       year
California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [88]:
pop['state']

KeyError: 'state'

In [90]:
pop.index['year']

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

In [91]:
index = pd.MultiIndex.from_product([[2013,2014],[1,2]],names = ['year','visit'])

In [92]:
index

MultiIndex([(2013, 1),
            (2013, 2),
            (2014, 1),
            (2014, 2)],
           names=['year', 'visit'])

In [93]:
index[0]

(2013, 1)

In [94]:
index['year']

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

In [95]:
index.year

AttributeError: 'MultiIndex' object has no attribute 'year'

In [96]:
index.names

FrozenList(['year', 'visit'])

In [97]:
columns = pd.MultiIndex.from_product([['An','Ba','Ve'],['HR','temp']],names=['subject','type'])

In [98]:
columns

MultiIndex([('An',   'HR'),
            ('An', 'temp'),
            ('Ba',   'HR'),
            ('Ba', 'temp'),
            ('Ve',   'HR'),
            ('Ve', 'temp')],
           names=['subject', 'type'])

In [99]:
np.random.randn(4,6)

array([[-0.80245888, -0.32439121, -0.6245069 , -0.5685529 ,  1.37976612,
         2.06875772],
       [-0.25206578,  2.47911365, -0.58907488, -0.82324463, -0.29222653,
         1.09429023],
       [ 0.13925701, -0.49604822,  0.10258522,  1.28576021,  0.09969016,
        -0.61806033],
       [ 0.68554793, -0.95645963, -0.45508328, -0.4316341 , -2.48324565,
         0.04813707]])

In [100]:
np.round(np.random.randn(4,6),1)

array([[-0.2,  0.4,  0.2,  0.5, -0.2,  0.6],
       [-0.3, -1.4,  0.5,  1. , -1.4, -0.6],
       [-0.5, -1. ,  0.2,  0.6, -0.2,  0. ],
       [-0.4,  2. ,  0.3,  2.3,  0.2,  0.1]])

In [101]:
data = np.round(np.random.randn(4,6),1)

In [102]:
data[:,::2]

array([[-0.9,  0.4, -1.2],
       [ 1.1, -0. ,  1.5],
       [ 0.1, -0.9, -0.6],
       [ 1.1, -1.9,  1. ]])

In [103]:
data

array([[-0.9, -1.1,  0.4, -0.1, -1.2,  0.2],
       [ 1.1,  1.5, -0. , -0.5,  1.5, -0.8],
       [ 0.1,  1.3, -0.9, -1.5, -0.6, -0.4],
       [ 1.1, -0.3, -1.9, -0.9,  1. , -1.2]])

In [104]:
data[:,::2] *= 10
data

array([[ -9. ,  -1.1,   4. ,  -0.1, -12. ,   0.2],
       [ 11. ,   1.5,  -0. ,  -0.5,  15. ,  -0.8],
       [  1. ,   1.3,  -9. ,  -1.5,  -6. ,  -0.4],
       [ 11. ,  -0.3, -19. ,  -0.9,  10. ,  -1.2]])

In [105]:
data += 37
data

array([[28. , 35.9, 41. , 36.9, 25. , 37.2],
       [48. , 38.5, 37. , 36.5, 52. , 36.2],
       [38. , 38.3, 28. , 35.5, 31. , 36.6],
       [48. , 36.7, 18. , 36.1, 47. , 35.8]])

In [106]:
healt_data = pd.DataFrame(data,index=index,columns=columns)

In [107]:
healt_data

subject       An          Ba          Ve      
type          HR  temp    HR  temp    HR  temp
year visit                                    
2013 1      28.0  35.9  41.0  36.9  25.0  37.2
     2      48.0  38.5  37.0  36.5  52.0  36.2
2014 1      38.0  38.3  28.0  35.5  31.0  36.6
     2      48.0  36.7  18.0  36.1  47.0  35.8

In [108]:
healt_data['An']

type          HR  temp
year visit            
2013 1      28.0  35.9
     2      48.0  38.5
2014 1      38.0  38.3
     2      48.0  36.7

In [111]:
healt_data['HR']

KeyError: 'HR'

In [112]:
type(healt_data['An'])

pandas.core.frame.DataFrame

In [113]:
type(healt_data['An']['HR'])

pandas.core.series.Series

In [114]:
healt_data['An']['HR']

year  visit
2013  1        28.0
      2        48.0
2014  1        38.0
      2        48.0
Name: HR, dtype: float64

In [115]:
healt_data['An']['HR'][2013]

visit
1    28.0
2    48.0
Name: HR, dtype: float64

In [118]:
healt_data['An']['HR'][2013][1]

28.0

In [121]:
healt_data['An'].loc[2013]

type     HR  temp
visit            
1      28.0  35.9
2      48.0  38.5

In [122]:
pop

state       year
California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [123]:
pop.loc['California':'New York']

state       year
California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
dtype: int64

In [124]:
healt_data

subject       An          Ba          Ve      
type          HR  temp    HR  temp    HR  temp
year visit                                    
2013 1      28.0  35.9  41.0  36.9  25.0  37.2
     2      48.0  38.5  37.0  36.5  52.0  36.2
2014 1      38.0  38.3  28.0  35.5  31.0  36.6
     2      48.0  36.7  18.0  36.1  47.0  35.8

In [127]:
healt_data['An','HR']

year  visit
2013  1        28.0
      2        48.0
2014  1        38.0
      2        48.0
Name: (An, HR), dtype: float64

In [128]:
healt_data.iloc[:,:]

subject       An          Ba          Ve      
type          HR  temp    HR  temp    HR  temp
year visit                                    
2013 1      28.0  35.9  41.0  36.9  25.0  37.2
     2      48.0  38.5  37.0  36.5  52.0  36.2
2014 1      38.0  38.3  28.0  35.5  31.0  36.6
     2      48.0  36.7  18.0  36.1  47.0  35.8

In [129]:
healt_data.iloc[:2,:2]

subject       An      
type          HR  temp
year visit            
2013 1      28.0  35.9
     2      48.0  38.5

In [130]:
healt_data.iloc[1:,:]

subject       An          Ba          Ve      
type          HR  temp    HR  temp    HR  temp
year visit                                    
2013 2      48.0  38.5  37.0  36.5  52.0  36.2
2014 1      38.0  38.3  28.0  35.5  31.0  36.6
     2      48.0  36.7  18.0  36.1  47.0  35.8

In [131]:
healt_data.iloc[:2,('Ba')]

ValueError: Location based indexing can only have [integer, integer slice (START point is INCLUDED, END point is EXCLUDED), listlike of integers, boolean array] types

In [132]:
healt_data.iloc[:2,('Ba','HR')]

IndexingError: Too many indexers

In [137]:
healt_data.loc[2013,('Ba','HR')]

visit
1    41.0
2    37.0
Name: (Ba, HR), dtype: float64

In [138]:
type(healt_data.loc[2013,('Ba','HR')])

pandas.core.series.Series

In [143]:
healt_data.loc[2013,('Ba','HR')][2]

37.0

In [144]:
idx = pd.IndexSlice

In [145]:
idx

In [147]:
idx[:,1]

(slice(None, None, None), 1)

In [148]:
idx[:,'HR']

(slice(None, None, None), 'HR')

In [150]:
healt_data.loc[idx[:,1],idx[:,'HR']]

subject       An    Ba    Ve
type          HR    HR    HR
year visit                  
2013 1      28.0  41.0  25.0
2014 1      38.0  28.0  31.0

In [156]:
healt_data.iloc[:,1]

year  visit
2013  1        35.9
      2        38.5
2014  1        38.3
      2        36.7
Name: (An, temp), dtype: float64

In [155]:
healt_data

subject       An          Ba          Ve      
type          HR  temp    HR  temp    HR  temp
year visit                                    
2013 1      28.0  35.9  41.0  36.9  25.0  37.2
     2      48.0  38.5  37.0  36.5  52.0  36.2
2014 1      38.0  38.3  28.0  35.5  31.0  36.6
     2      48.0  36.7  18.0  36.1  47.0  35.8

In [158]:
healt_data.loc[idx[2013,:],idx[:,'HR']].mean()

subject  type
An       HR      38.0
Ba       HR      39.0
Ve       HR      38.5
dtype: float64

In [160]:
index = pd.MultiIndex.from_product([['a','c','b'],[1,2]])

In [162]:
data = pd.DataFrame(np.random.rand(6),index=index)

In [163]:
data

0
a 1  0.190028
  2  0.842469
c 1  0.033497
  2  0.910217
b 1  0.526068
  2  0.913675

In [164]:
data.index.names = ['char','int']

In [165]:
data

0
char int          
a    1    0.190028
     2    0.842469
c    1    0.033497
     2    0.910217
b    1    0.526068
     2    0.913675

In [166]:
data['a':'c']

UnsortedIndexError: 'Key length (1) was greater than MultiIndex lexsort depth (0)'

In [167]:
data

0
char int          
a    1    0.190028
     2    0.842469
c    1    0.033497
     2    0.910217
b    1    0.526068
     2    0.913675

In [168]:
data.sort_index()

0
char int          
a    1    0.190028
     2    0.842469
b    1    0.526068
     2    0.913675
c    1    0.033497
     2    0.910217

In [169]:
data = data.sort_index()

In [170]:
data

0
char int          
a    1    0.190028
     2    0.842469
b    1    0.526068
     2    0.913675
c    1    0.033497
     2    0.910217

In [171]:
data['a':'c']

0
char int          
a    1    0.190028
     2    0.842469
b    1    0.526068
     2    0.913675
c    1    0.033497
     2    0.910217

In [172]:
index = pd.MultiIndex.from_product([['a','c','b'],[1,2]])
data = pd.DataFrame(np.random.rand(6),index=index)
data.index.names = ['char','int']
data

0
char int          
a    1    0.034687
     2    0.426223
c    1    0.362654
     2    0.087726
b    1    0.948883
     2    0.562922

In [179]:
data.loc[idx[0:,:]]

UnsortedIndexError: 'Key length (1) was greater than MultiIndex lexsort depth (0)'

In [180]:
pop

state       year
California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [181]:
pop_flat = pop.unstack()

In [182]:
pop_flat

year            2000      2010
state                         
California  33871648  37253956
New York    18976457  19378102
Texas       20851820  25145561

In [183]:
pop_flat = pop.reset_index(name='population')

In [184]:
pop_flat

state  year  population
0  California  2000    33871648
1  California  2010    37253956
2    New York  2000    18976457
3    New York  2010    19378102
4       Texas  2000    20851820
5       Texas  2010    25145561

In [187]:
pop_flat.set_index(['state','year'])

population
state      year            
California 2000    33871648
           2010    37253956
New York   2000    18976457
           2010    19378102
Texas      2000    20851820
           2010    25145561

In [188]:
pop

state       year
California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [192]:
pop.reset_index()

state  year         0
0  California  2000  33871648
1  California  2010  37253956
2    New York  2000  18976457
3    New York  2010  19378102
4       Texas  2000  20851820
5       Texas  2010  25145561

In [195]:
type(Out[192]['state'])

pandas.core.series.Series

In [196]:
healt_data

subject       An          Ba          Ve      
type          HR  temp    HR  temp    HR  temp
year visit                                    
2013 1      28.0  35.9  41.0  36.9  25.0  37.2
     2      48.0  38.5  37.0  36.5  52.0  36.2
2014 1      38.0  38.3  28.0  35.5  31.0  36.6
     2      48.0  36.7  18.0  36.1  47.0  35.8

In [197]:
healt_data.mean()

subject  type
An       HR      40.50
         temp    37.35
Ba       HR      31.00
         temp    36.25
Ve       HR      38.75
         temp    36.45
dtype: float64

In [198]:
healt_data.mean(level='year')

subject    An          Ba          Ve      
type       HR  temp    HR  temp    HR  temp
year                                       
2013     38.0  37.2  39.0  36.7  38.5  36.7
2014     43.0  37.5  23.0  35.8  39.0  36.2

In [199]:
healt_data.mean(level='visit')

subject    An          Ba          Ve      
type       HR  temp    HR  temp    HR  temp
visit                                      
1        33.0  37.1  34.5  36.2  28.0  36.9
2        48.0  37.6  27.5  36.3  49.5  36.0

In [ ]:
!git add .
!git commit -m "Hierarchical Indexing"
!git push
!git status